spring:
  application:
    name: OnlineRetailSystem
  datasource:
    url: jdbc:sqlserver://cs544.cs.miu.edu:1433;databaseName=CS544-202305-04;trustServerCertificate=true
    username: CS544-202305-04
    password: 42c67741
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
server:
  port: 9099
